apiVersion: v1
baseDomain: ran.samsung.bos2.lab
compute:
- architecture: amd64 
  hyperthreading: Enabled
  name: worker
  replicas: 1
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata:
  name: saumsungran
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 192.168.40.0/25
  networkType: OVNKubernetes 
  serviceNetwork:
  - 172.30.0.0/16
platform: 
  baremetal:
    apiVIPs:
    - 192.168.40.70
    ingressVIPs:
    - 192.168.40.71
pullSecret: '{"auths":{"10.16.33.251:30050":{"auth":"<redacted>"},"registry.example.com:443":{"auth":"<redacted>"},"quay-1.l1pz-espoo.example.com":{"auth":"<redacted>"},"quay-2.l1pz-espoo.example.com":{"auth":"<redacted>"}}}' 
sshKey: 'ssh-rsa AAAA<redacted> user@work'
imageContentSources:
  - mirrors:
    - quay-2.l1pz-espoo.example.com/unbox/openshift/release
    source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
  - mirrors:
    - quay-2.l1pz-espoo.example.com/unbox/openshift/release-images
    source: quay.io/openshift-release-dev/ocp-release
additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
  <redacted>
  -----END CERTIFICATE-----

