---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  name: thanos-object-storage
  namespace: open-cluster-management-observability
type: Opaque
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: thanos-s3-b148ee40-4d41-45fd-8de0-b93f21f60875        # e.g. observability-bucket
      endpoint: "s3.openshift-storage.svc"     # internal NooBaa RGW endpoint
      insecure: false
      access_key: FnvfX16CLvAlk5uDBqoy
      secret_key: afC/RqKlbDW3G9Opezn78Sbcbr7zXeR+XyBbW5Eq
      http_config:
        tls_config:
          ca_file: "/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt"
