---
apiVersion: ocs.openshift.io/v1
kind: OCSInitialization
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: ocsinit
  namespace: openshift-storage
spec:
  enableCephTools: true
---
apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: ocs-storagecluster
  namespace: openshift-storage
spec:
  arbiter: {}
  enableCephTools: true
  encryption:
    keyRotation:
      schedule: '@weekly'
    kms: {}
  externalStorage: {}
  managedResources:
    cephBlockPools:
      reconcileStrategy: manage
    cephCluster: {}
    cephConfig: {}
    cephDashboard: {}
    cephFilesystems:
      dataPoolSpec:
        application: ""
        erasureCoded:
          codingChunks: 0
          dataChunks: 0
        mirroring: {}
        quotas: {}
        replicated:
          size: 0
        statusCheck:
          mirror: {}
      reconcileStrategy: manage
    cephNonResilientPools:
      count: 1
      resources: {}
      volumeClaimTemplate:
        metadata: {}
        spec:
          resources: {}
        status: {}
    cephObjectStoreUsers:
      reconcileStrategy: manage
    cephObjectStores:
      reconcileStrategy: manage
    cephRBDMirror:
      daemonCount: 1
    cephToolbox: {}
  mirroring: {}
  monDataDirHostPath: /var/lib/rook
  multiCloudGateway:
    reconcileStrategy: manage
  network:
    ipFamily: IPv4
    multiClusterService: {}
  storageDeviceSets:
  - config: {}
    count: 1
    dataPVCTemplate:
      metadata: {}
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: "1"
        storageClassName: localblock
        volumeMode: Block
      status: {}
    name: ocs-deviceset
    placement: {}
    preparePlacement: {}
    replica: 3
    resources: {}
---
apiVersion: odf.openshift.io/v1alpha1
kind: StorageSystem
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
  - storagesystem.odf.openshift.io
  name: ocs-storagecluster-storagesystem
  namespace: openshift-storage
spec:
  kind: storagecluster.ocs.openshift.io/v1
  name: ocs-storagecluster
  namespace: openshift-storage

