---
apiVersion: local.storage.openshift.io/v1
kind: LocalVolume
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: local-block
  namespace: openshift-local-storage
spec:
  logLevel: Normal
  managementState: Managed
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
      - key: kubernetes.io/hostname
        operator: In
        values:
        - master0.ran.samsung.bos2.lab
        - master1.ran.samsung.bos2.lab
        - master2.ran.samsung.bos2.lab
  storageClassDevices:
  - devicePaths:
    - /dev/disk/by-path/pci-0000:65:00.0-scsi-0:2:1:0
    storageClassName: localblock
    volumeMode: Block

