apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-kafka-cluster
  namespace: openshift-amq-streams
spec:
  kafka:
    replicas: 3
    version: 3.8.0
    config:
      log.message.format.version: "3.8"
      inter.broker.protocol.version: "3.8"
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
