---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hub-operators-deployment
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: hub-config/operators-deployment
    repoURL: 'https://github.com/obochan-rh/midu-l1-cp.git'
    targetRevision: ofersamsungran-test 
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 1
        maxDuration: 3m0s
      limit: 1000
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hub-operators-config
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: hub-config/operators-config/connected
    repoURL: 'https://github.com/obochan-rh/midu-l1-cp.git'
    targetRevision: ofersamsungran-test 
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 1
        maxDuration: 3m0s
      limit: 1000
  ignoreDifferences:
    - group: operator.open-cluster-management.io
      kind: MultiClusterHub
      jsonPointers:
        - /spec/overrides/components  
