---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  labels:
    kubernetes.io/metadata.name: ibu-odf-s3-storage
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource
  name: ibu-odf-s3-storage
spec:
  finalizers:
  - kubernetes
---
apiVersion: noobaa.io/v1alpha1
kind: NooBaa
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource
  name: noobaa
  namespace: ibu-odf-s3-storage
spec:
  coreResources:
    requests:
      cpu: "1"
      memory: 1Gi
    limits:
      cpu: "2"
      memory: 2Gi
  dbResources:
    requests:
      cpu: "1"
      memory: 1Gi
    limits:
      cpu: "2"
      memory: 2Gi
