---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: thanos-s3
  namespace: open-cluster-management-observability
spec:
  generateBucketName: thanos-s3
  storageClassName: openshift-storage.noobaa.io

