---
apiVersion: v1
kind: Secret
metadata:
  name: thanos-s3
  namespace: open-cluster-management-observability
  annotations:
    argocd.argoproj.io/sync-wave: "10"
type: Opaque
data:
  AWS_ACCESS_KEY_ID: N01qajVNN0tVMmtPc3dUUmNQRW4=
  AWS_SECRET_ACCESS_KEY: M3RZNTV3MjdjUytUOEVQUkpWTG1NVTZBMkNKNTVSL1ZaWFk5VTluUg==
